# Generated by Django 3.0.5 on 2020-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
