# Generated by Django 3.0.5 on 2020-05-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_curriculum_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='is_public',
            new_name='public',
        ),
    ]
