# Generated by Django 3.0.5 on 2020-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_auto_20200507_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='education_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
