# Generated by Django 3.0.5 on 2020-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0005_curriculum_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='education_level',
            field=models.CharField(default='', max_length=100),
        ),
    ]
