# Generated by Django 3.0.5 on 2020-06-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_auto_20200602_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='education_level',
            new_name='isced_level',
        ),
    ]
