# Generated by Django 3.0.5 on 2020-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_auto_20200606_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
