# Generated by Django 3.0.5 on 2020-09-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonCatVerb',
        ),
    ]
