# Generated by Django 3.0.5 on 2020-09-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0019_auto_20200522_2239'),
        ('verbs', '0002_delete_noncatverb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCatVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('curriculum_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_cat_verbs', to='analyses.CurriculumAnalysis')),
            ],
            options={
                'verbose_name': 'Non Categorised Verb',
                'verbose_name_plural': 'Non Categorised Verbs',
            },
        ),
    ]
