# Generated by Django 3.0.5 on 2020-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0019_auto_20200522_2239'),
        ('verbs', '0003_noncatverb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncatverb',
            name='curriculum_analysis',
        ),
        migrations.AddField(
            model_name='noncatverb',
            name='curriculum_analysises',
            field=models.ManyToManyField(related_name='non_cat_verbs', to='analyses.CurriculumAnalysis'),
        ),
    ]
