# Generated by Django 3.0.5 on 2020-09-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0004_auto_20200922_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noncatverb',
            old_name='curriculum_analysises',
            new_name='curriculum_analyses',
        ),
    ]
