# Generated by Django 3.0.5 on 2020-04-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0002_curriculum_date_created'),
        ('taxonomies', '0007_auto_20200426_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.Curriculum')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomies.CustomUserTaxonomy')),
            ],
            options={
                'verbose_name': 'Curriculum Analysis',
                'verbose_name_plural': 'Curriculum Analyses',
            },
        ),
    ]
