# Generated by Django 3.0.5 on 2020-04-28 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_date_created'),
        ('strands', '0001_initial'),
        ('learning_outcomes', '0001_initial'),
        ('taxonomies', '0007_auto_20200426_0619'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumanalysis',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_analyses', to='curricula.Curriculum'),
        ),
        migrations.AlterField(
            model_name='curriculumanalysis',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_analyses', to='taxonomies.CustomUserTaxonomy'),
        ),
        migrations.CreateModel(
            name='StrandAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('curriculum_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_analyses', to='analyses.CurriculumAnalysis')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_analyses', to='strands.Strand')),
            ],
            options={
                'verbose_name': 'Strand Analysis',
                'verbose_name_plural': 'Strand Analyses',
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_analyses', to='learning_outcomes.LearningOutcome')),
                ('strand_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_analyses', to='analyses.StrandAnalysis')),
            ],
            options={
                'verbose_name': 'Learning Outcome Analysis',
                'verbose_name_plural': 'Learning Outcome Analyses',
            },
        ),
    ]
