# Generated by Django 3.0.5 on 2020-04-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_categoryhit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryhit',
            old_name='count',
            new_name='frequency_count',
        ),
    ]
