# Generated by Django 3.0.5 on 2020-04-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_auto_20200428_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeCategoryHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('frequency_count', models.PositiveIntegerField(default=0)),
                ('learning_outcome_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_category_hit_counts', to='analyses.LearningOutcomeAnalysis')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryHit',
        ),
    ]
