# Generated by Django 3.0.5 on 2020-04-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_auto_20200428_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strandcategoryoccurrence',
            old_name='title',
            new_name='category',
        ),
    ]
