# Generated by Django 3.0.5 on 2020-04-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0007_auto_20200428_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strandcategoryoccurrence',
            name='strand_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_category_occurrences', to='analyses.StrandAnalysis'),
        ),
    ]
