# Generated by Django 3.0.5 on 2020-05-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0010_strandverbaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrandCategoryDiversityAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_average', models.FloatField(default=0)),
                ('strand_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_category_diversity_averages', to='analyses.StrandAnalysis')),
            ],
        ),
    ]
