# Generated by Django 3.0.5 on 2020-05-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_strandcategorydiversityaverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcomecategoryhitcount',
            name='learning_outcome_analysis',
        ),
        migrations.RemoveField(
            model_name='strandanalysis',
            name='curriculum_analysis',
        ),
        migrations.RemoveField(
            model_name='strandanalysis',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='strandcategorydiversity',
            name='strand_analysis',
        ),
        migrations.RemoveField(
            model_name='strandcategorydiversityaverage',
            name='strand_analysis',
        ),
        migrations.RemoveField(
            model_name='strandcategoryoccurrence',
            name='strand_analysis',
        ),
        migrations.RemoveField(
            model_name='strandverbaverage',
            name='strand_analysis',
        ),
        migrations.DeleteModel(
            name='LearningOutcomeAnalysis',
        ),
        migrations.DeleteModel(
            name='LearningOutcomeCategoryHitCount',
        ),
        migrations.DeleteModel(
            name='StrandAnalysis',
        ),
        migrations.DeleteModel(
            name='StrandCategoryDiversity',
        ),
        migrations.DeleteModel(
            name='StrandCategoryDiversityAverage',
        ),
        migrations.DeleteModel(
            name='StrandCategoryOccurrence',
        ),
        migrations.DeleteModel(
            name='StrandVerbAverage',
        ),
    ]
