# Generated by Django 3.0.5 on 2020-05-21 18:23

from django.db import migrations, models
import django.db.models.deletion
import utils.get


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0003_auto_20200507_1447'),
        ('analyses', '0012_auto_20200520_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrandAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('curriculum_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_analyses', to='analyses.CurriculumAnalysis')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_analyses', to='strands.Strand')),
            ],
            options={
                'verbose_name': 'Strand Analysis',
                'verbose_name_plural': 'Strand Analyses',
            },
            bases=(models.Model, utils.get.AnalysisGetMethods),
        ),
    ]
