# Generated by Django 3.0.5 on 2020-05-21 18:53

from django.db import migrations, models
import django.db.models.deletion
import utils.get


class Migration(migrations.Migration):

    dependencies = [
        ('learning_outcomes', '0001_initial'),
        ('analyses', '0013_strandanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_analyses', to='learning_outcomes.LearningOutcome')),
                ('strand_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_analyses', to='analyses.StrandAnalysis')),
            ],
            options={
                'verbose_name': 'Learning Outcome Analysis',
                'verbose_name_plural': 'Learning Outcome Analyses',
            },
            bases=(models.Model, utils.get.AnalysisGetMethods),
        ),
    ]
