# Generated by Django 3.0.5 on 2020-05-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0015_learningoutcomecategoryhits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeCategoryHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('learning_outcome_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_category_hit_counts', to='analyses.LearningOutcomeAnalysis')),
            ],
        ),
        migrations.CreateModel(
            name='StrandCategoryHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('strand_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_category_occurrences', to='analyses.StrandAnalysis')),
            ],
        ),
        migrations.DeleteModel(
            name='LearningOutcomeCategoryHits',
        ),
    ]
