# Generated by Django 3.0.5 on 2020-05-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0016_auto_20200521_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrandCategoryDiversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(default=0)),
                ('num_learning_outcomes', models.PositiveIntegerField(default=0)),
                ('strand_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_category_diversities', to='analyses.StrandAnalysis')),
            ],
        ),
    ]
