# Generated by Django 3.0.5 on 2020-05-22 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0018_strandaverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strandcategorydiversity',
            old_name='category_number',
            new_name='num_categories',
        ),
        migrations.AlterField(
            model_name='strandcategoryhitcount',
            name='strand_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strand_category_hit_counts', to='analyses.StrandAnalysis'),
        ),
    ]
