# Generated by Django 3.0.5 on 2020-04-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0002_curriculum_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('learning_outcome_list', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curricula.Curriculum')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
            },
        ),
    ]
