# Generated by Django 3.0.5 on 2020-05-07 12:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strand',
            name='color',
            field=colorfield.fields.ColorField(default='#444444', max_length=18),
        ),
    ]
