# Generated by Django 3.0.5 on 2020-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0002_strand_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strand',
            name='color',
        ),
        migrations.AddField(
            model_name='strand',
            name='colour',
            field=models.CharField(default='#444444', max_length=7),
        ),
    ]
