# Generated by Django 3.0.5 on 2020-04-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertaxonomy',
            name='slug',
            field=models.CharField(default='', max_length=150, null=True, unique=True),
        ),
    ]
