# Generated by Django 3.0.5 on 2020-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_auto_20200424_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertaxonomy',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
