# Generated by Django 3.0.5 on 2020-04-24 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomies', '0004_auto_20200424_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertaxonomy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_taxonomies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VerbCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_categories', to='taxonomies.CustomUserTaxonomy')),
            ],
            options={
                'verbose_name': 'Verb Category',
                'verbose_name_plural': 'Verb Categories',
            },
        ),
    ]
