# Generated by Django 3.0.5 on 2020-04-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0005_auto_20200424_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbcategory',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('verb_categories', models.ManyToManyField(to='taxonomies.VerbCategory')),
            ],
            options={
                'verbose_name': 'Verb',
                'verbose_name_plural': 'Verbs',
            },
        ),
    ]
