# Generated by Django 3.0.5 on 2020-04-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0006_auto_20200424_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbcategory',
            name='taxonomy',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
        migrations.DeleteModel(
            name='VerbCategory',
        ),
    ]
