# Generated by Django 3.0.5 on 2020-06-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0007_auto_20200426_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertaxonomy',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
