# Generated by Django 3.0.5 on 2020-04-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='container',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='KeyValuePair',
        ),
    ]
