# Generated by Django 3.0.5 on 2020-04-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomies', '0007_auto_20200426_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('verb_list', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_categories', to='taxonomies.CustomUserTaxonomy')),
            ],
            options={
                'verbose_name': 'Verb Category',
                'verbose_name_plural': 'Verb Categories',
            },
        ),
    ]
