# Generated by Django 3.0.5 on 2020-06-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verb_categories', '0003_auto_20200603_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verbcategory',
            unique_together=set(),
        ),
    ]
