# Generated by Django 3.0.5 on 2020-06-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0007_auto_20200426_0619'),
        ('verb_categories', '0004_auto_20200603_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verbcategory',
            unique_together={('taxonomy', 'level')},
        ),
    ]
